vec3 blocklightColSqrt = vec3(BLOCKLIGHT_R, BLOCKLIGHT_G, BLOCKLIGHT_B) * BLOCKLIGHT_I / 255.0;
vec3 blocklightCol = blocklightColSqrt * blocklightColSqrt;

#if COLORED_LIGHTING_MODE == 3 || COLORED_LIGHTING_MODE == 4
vec3 SOUL_TORCHColSqrt = vec3(SOUL_TORCH_R, SOUL_TORCH_G, SOUL_TORCH_B) * SOUL_TORCH_I / 255.0;
vec3 SOUL_TORCH = SOUL_TORCHColSqrt * SOUL_TORCHColSqrt;

vec3 TORCHColSqrt = vec3(TORCH_R, TORCH_G, TORCH_B) * TORCH_I / 255.0;
vec3 TORCH = TORCHColSqrt * TORCHColSqrt;

vec3 REDSTONE_TORCHColSqrt = vec3(REDSTONE_TORCH_R, REDSTONE_TORCH_G, REDSTONE_TORCH_B) * REDSTONE_TORCH_I / 255.0;
vec3 REDSTONE_TORCH = REDSTONE_TORCHColSqrt * REDSTONE_TORCHColSqrt;

vec3 JACKOLANTERNColSqrt = vec3(JACKOLANTERN_R, JACKOLANTERN_G, JACKOLANTERN_B) * JACKOLANTERN_I / 255.0;
vec3 JACKOLANTERN = JACKOLANTERNColSqrt * JACKOLANTERNColSqrt;

vec3 SHROOMLIGHTColSqrt = vec3(SHROOMLIGHT_R, SHROOMLIGHT_G, SHROOMLIGHT_B) * SHROOMLIGHT_I / 255.0;
vec3 SHROOMLIGHT = SHROOMLIGHTColSqrt * SHROOMLIGHTColSqrt;

vec3 LAVAColSqrt = vec3(LAVA_R, LAVA_G, LAVA_B) * LAVA_I / 255.0;
vec3 LAVA = LAVAColSqrt * LAVAColSqrt;

vec3 GLOWSTONEColSqrt = vec3(GLOWSTONE_R, GLOWSTONE_G, GLOWSTONE_B) * GLOWSTONE_I / 255.0;
vec3 GLOWSTONE = GLOWSTONEColSqrt * GLOWSTONEColSqrt;

vec3 SEA_LANTERNColSqrt = vec3(SEA_LANTERN_R, SEA_LANTERN_G, SEA_LANTERN_B) * SEA_LANTERN_I / 255.0;
vec3 SEA_LANTERN = SEA_LANTERNColSqrt * SEA_LANTERNColSqrt;

vec3 END_RODColSqrt = vec3(END_ROD_R, END_ROD_G, END_ROD_B) * END_ROD_I / 255.0;
vec3 END_ROD = END_RODColSqrt * END_RODColSqrt;

vec3 BEACONColSqrt = vec3(BEACON_R, BEACON_G, BEACON_B) * BEACON_I / 255.0;
vec3 BEACON = BEACONColSqrt * BEACONColSqrt;
#endif